### ISSUE TITLE
Replay Mode shortcut conflicts with Nintendo button layout

### ISSUE THREAD

**Issue by tulang3587** [marissa999/decky-recorder#14]
The shortcut to enable replay more in the version 0.2.0 of the Deck Recorder conflicts with the shortcut to display keyboard when you use the Nintendo button layout on the Steam Deck settings.

**Comment by safijari** [comment]
Noted.

Also from Reddit: the OG steam controller apparently turns off with this combo.

**Comment by Jademalo** [comment]
As a suggestion @safijari, is it possible to have the bind be RT hold?
That would be similar to how it works on the Switch, where a tap is a screenshot and a hold saves a video clip.

**Comment by safijari** [comment]
> As a suggestion @safijari, is it possible to have the bind be RT hold? That would be similar to how it works on the Switch, where a tap is a screenshot and a hold saves a video clip.

That's unfortunately not doable as there's no way that I know of to tell Steam to not take a screenshot. So, I guess it _is_ doable but I imagine an extra screenshot with every recording might get annoying. I have updated it to Steam + Start in https://github.com/marissa999/decky-recorder/pull/16 . Hopefully that's a better choice.

**Comment by Jademalo** [comment]
Ah damn, that's a shame!

**Comment by safijari** [comment]
Changed to Steam + Start in latest testing release.
