### ISSUE TITLE
video not being made

### ISSUE THREAD

**Issue by LhymeFruit** [marissa999/decky-recorder#2]
no video is made after recording

**Comment by marissa999** [comment]
That shouldnt happen hmm. I am currently busy until the weekend but could you tell me your

SteamOS-Version
Decky-Loader Version
Decky-Recorder Version and if you used the release zip or built it yourself

And if possible can you also try to send me the content of the following files after the error occurred (those files get deleted between reboots):
/tmp/decky-recorder.log
/tmp/decky-recorder-std-out.log
/tmp/decky-recorder-std-err.log

Maybe I can see why it is happening :thinking:

**Comment by omnom143** [comment]
> That shouldnt happen hmm. I am currently busy until the weekend but could you tell me your
> 
> SteamOS-Version Decky-Loader Version Decky-Recorder Version and if you used the release zip or built it yourself
> 
> And if possible can you also try to send me the content of the following files after the error occurred (those files get deleted between reboots): /tmp/decky-recorder.log /tmp/decky-recorder-std-out.log /tmp/decky-recorder-std-err.log
> 
> Maybe I can see why it is happening 🤔

its not an error there is no error its like just not working

**Comment by CreatorAndrew** [comment]
I am having the same issue in version 0.0.3. It happens randomly, around 50% of the time. It wasn't happening in version 0.0.2, so I believe it has something to do with ffmpeg copying the file.
[decky-recorder-std-err.log](https://github.com/marissa999/decky-recorder/files/10460807/decky-recorder-std-err.log)
[decky-recorder-std-out.log](https://github.com/marissa999/decky-recorder/files/10460808/decky-recorder-std-out.log)
[decky-recorder.log](https://github.com/marissa999/decky-recorder/files/10460809/decky-recorder.log)

**Comment by marissa999** [comment]
> its not an error there is no error its like just not working
That sounds like the python backend is not loading properly then if it doesnt even log anything into those files hmm. Ill need to try to figure out why that happened :thinking: 

> I am having the same issue in version 0.0.3. It happens randomly, around 50% of the time. It wasn't happening in version 0.0.2, so I believe it has something to do with ffmpeg copying the file.
But you have logs, which I believe this might be a different issue. I noticed i have the same issue too in fact :thinking: But thank you for the logs! 
"ERROR: from element /GstPipeline:pipeline0/GstMP4Mux:sink: Could not multiplex stream."
I wonder if gst is maybe the issue here :thinking:

**Comment by lividhen** [comment]
This is also an issue with recapture.

**Comment by narren96c** [comment]
Not sure if it is the same issue as I'm having... Occasionally, I get recorded file broken with v0.0.2. FFMPEG claims that it contains no stream and the file is not playable. I had similar issues with recapture btw.

**Comment by marissa999** [comment]
Super late response, but if you download 0.0.4 from the plugin store I think it should be fixed now. I threw away most changes and restarted from a known good position. 

I had no issues with missing files, and somebody from the decky loader testing team also made 9 recordings for the last version without issues. So I'm pretty confident that it's working now. Hopefully

**Comment by baziklet** [comment]
Hello, I am having the same issue while trying to record videos that are over 30 minutes long, files are not being saved. 

OS Version 3.4.4
OS Build 20221228.1
Karnel Version 5.13.0-valve36-1-neptune
Decky Loader version: v2.6.1
Decky Recorder: 0.1.0

[decky-recorder-std-err.log](https://github.com/marissa999/decky-recorder/files/10834116/decky-recorder-std-err.log)
[decky-recorder-std-out.log](https://github.com/marissa999/decky-recorder/files/10834117/decky-recorder-std-out.log)
[decky-recorder.log](https://github.com/marissa999/decky-recorder/files/10834118/decky-recorder.log)

**Comment by RealDoomSlaya** [comment]
@ marissa999 I decided to comment here...ended up recording an hour-long video,, and it worked perfectly! I was testing it on my overclocked deck, TWD Definitive edition, on max settings...ran perfectly, mostly 60 fps. Maybe a 5-10fps drop. 

Other than the video uploading in 360p...it worked perfectly, I will definitely be using this later on!
https://www.youtube.com/watch?v=CuDlQXiES4I
