### ISSUE TITLE
"Too early to record another clip"

### ISSUE THREAD

**Issue by MissingNerd** [marissa999/decky-recorder#22]
The plugin used to work for a few clips but now I always get this error message. Not linked to any particular game. My deck is also pretty vanilla since I just got a replacement model. Decky Recorder is basically the only non-stock thing I use.

**Comment by safijari** [comment]
Is this fixed if you reboot? Also are you on stable, beta, or preview?

**Comment by safijari** [comment]
Closing in favor of #25
