### ISSUE TITLE
Replays don't save anywhere

### ISSUE THREAD

**Issue by MediaWithMiles** [marissa999/decky-recorder#23]
Even when I press the options and not the Steam + Start.

**Comment by safijari** [comment]
Does the notification say "Clip Saved"? Or is there no notification?

**Comment by MediaWithMiles** [comment]
So, Steam + Y just turns off the enabler and Steam + Start doesn’t do anything at all. So when I press the 30 seconds or 1 min, it flashes then nothing.

**Comment by safijari** [comment]
Closing in favor of #25

**Comment by MediaWithMiles** [comment]
??

**Comment by UnexaZ** [comment]
Keeping past messages in the desktop log without replays, no warnings and no files, seems to be inactive. (translated witch google)
