### ISSUE TITLE
[Bug] Recording process gets in a bad state when going to / from desktop mode

### ISSUE THREAD

**Issue by safijari** [marissa999/decky-recorder#25]
#24 should solve this

**Comment by irfanhakim-as** [comment]
> #24 should solve this

may i know if the fix from #24 has made its way to the default plugin store channel? i'm currently on `v0.2.0` n still getting the "Too early to record..." error.

**Comment by safijari** [comment]
@irfanhakim-as It hasn't yet. 0.2.2 will include it hopefully soon.

**Comment by EliasGagnef** [comment]
Getting "Too early to record" all the time even after restarting, is there any fix?
