### ISSUE TITLE
Steam + Y is the shortcut to turn off the external controller

### ISSUE THREAD

**Issue by wanieru** [marissa999/decky-recorder#31]
If I play with a PS5 controller, then pressing  Steam + Y (or rather PS + Triangle) will turn off the controller. This is Steam's shortcut, and I don't know if there's a way to turn it off. Pretty inconvevient when using an external controller.

That being said, I'm super excited to see to see something like this being developed!

**Comment by marissa999** [comment]
This is already fixed but it's not in the Decky Repository as of now. You can try to download and install https://github.com/marissa999/decky-recorder/releases/tag/0.2.1 manually. You only need to unzip and replace this with the version you have installed in /home/deck/homebrew/plugin

If you wanna check the progress of 0.2.1 getting uploaded to the Decky plugin database you can check it out here: https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/296

**Comment by mdPlusPlus** [comment]
Interestingly the Xbox button + Y doesn't shutoff the Xbox controller, so this seems to be PlayStation related.
