### ISSUE TITLE
capture not working when bluetooth earphone used.

### ISSUE THREAD

**Issue by Ozymandias1** [marissa999/decky-recorder#32]
capture not working when bluetooth earphone used.

record works fine when i use wired earphone or steamdeck speaker.

but, if i use bluetooth earphone, it's not work.

i tested airpods 3rd generation and cx350bt.

**Comment by safijari** [comment]
Does no video get saved? Or the video has no sound?

**Comment by Ozymandias1** [comment]
> Does no video get saved? Or the video has no sound?

video is not saved.
and also sometimes capture is not work on external display.

**Comment by aleksnidzelskiy** [comment]
Same issue

**Comment by jenkshi** [comment]
I have the same issue too

**Comment by azahariar** [comment]
same issues

**Comment by safijari** [comment]
Fixed but not deployed. Please take future conversation to the issue in the fork-repo
