### ISSUE TITLE
system crashing upon enabling Decky Recorder

### ISSUE THREAD

**Issue by pparmy** [marissa999/decky-recorder#51]
[decky-recorder.log](https://github.com/marissa999/decky-recorder/files/11471690/decky-recorder.log)
[decky-recorder-std-err.log](https://github.com/marissa999/decky-recorder/files/11471692/decky-recorder-std-err.log)
[decky-recorder-std-out.log](https://github.com/marissa999/decky-recorder/files/11471693/decky-recorder-std-out.log)

**Comment by pparmy** [comment]
Decky Recorder: 2023-05-14 05:35:49,243 INFO Successfully loaded psutil
Decky Recorder: 2023-05-14 05:35:49,244 INFO Loading config
Decky Recorder: 2023-05-14 05:36:17,682 INFO Is capturing? False
Decky Recorder: 2023-05-14 05:36:17,693 INFO Is Rolling? False
Decky Recorder: 2023-05-14 05:36:17,725 INFO Current mode: localFile
Decky Recorder: 2023-05-14 05:36:17,743 INFO Current local filepath: /home/deck/Videos
Decky Recorder: 2023-05-14 05:36:17,752 INFO Current local file format: mp4
Decky Recorder: 2023-05-14 05:36:19,852 INFO Enable rolling was called begin
Decky Recorder: 2023-05-14 05:36:19,852 INFO Is capturing? False
Decky Recorder: 2023-05-14 05:36:19,853 INFO Starting recording
Decky Recorder: 2023-05-14 05:36:19,853 INFO Starting recording for mp4 with mux mp4mux
Decky Recorder: 2023-05-14 05:36:19,853 INFO Is capturing? False
Decky Recorder: 2023-05-14 05:36:19,876 INFO Local File Recording
Decky Recorder: 2023-05-14 05:36:19,877 INFO Setting tmp filepath
Decky Recorder: 2023-05-14 05:36:19,877 INFO Setting local filepath
Decky Recorder: 2023-05-14 05:36:19,877 INFO Making audio pipeline
Decky Recorder: 2023-05-14 05:36:19,892 INFO Audio device output alsa_output.pci-0000_04_00.5-platform-acp5x_mach.0.HiFi__hw_acp5x_0__sink
Decky Recorder: 2023-05-14 05:36:19,892 INFO Command: GST_VAAPI_ALL_DRIVERS=1 GST_PLUGIN_PATH=/home/deck/homebrew/plugins/decky-recorder/bin/gstreamer-1.0 LD_LIBRARY_PATH=/home/deck/homebrew/plugins/decky-recorder/bin gst-launch-1.0 -e -vvv pipewiresrc do-timestamp=true ! vaapipostproc ! queue ! vaapih264enc ! h264parse ! splitmuxsink name=sink muxer=mp4mux muxer-pad-map=x-pad-map,audio=vid location=/dev/shm/Decky-Recorder-Rolling_%02d.mp4 max-size-time=2000000000 max-files=240 pulsesrc device="Recording_alsa_output.pci-0000_04_00.5-platform-acp5x_mach.0.HiFi__hw_acp5x_0__sink.monitor" ! audioconvert ! lamemp3enc target=bitrate bitrate=128 cbr=true ! sink.audio_0
Decky Recorder: 2023-05-14 05:36:19,893 INFO Recording started!
Decky Recorder: 2023-05-14 05:36:19,893 INFO Enable rolling was called end
Decky Recorder: 2023-05-14 05:36:54,856 INFO Is capturing? True
Decky Recorder: 2023-05-14 05:36:54,872 INFO Is Rolling? True
Decky Recorder: 2023-05-14 05:36:54,908 INFO Current mode: localFile
Decky Recorder: 2023-05-14 05:36:54,932 INFO Current local filepath: /home/deck/Videos
Decky Recorder: 2023-05-14 05:36:54,941 INFO Current local file format: mp4
Decky Recorder: 2023-05-14 05:36:56,956 INFO Disable rolling was called begin
Decky Recorder: 2023-05-14 05:36:56,956 INFO Is capturing? True
Decky Recorder: 2023-05-14 05:36:56,956 INFO Stopping recording
Decky Recorder: 2023-05-14 05:36:56,956 INFO Is capturing? True
Decky Recorder: 2023-05-14 05:36:56,956 INFO Sending sigin
Decky Recorder: 2023-05-14 05:36:56,956 INFO Sigin sent. Waiting...
Decky Recorder: 2023-05-14 05:36:56,956 INFO Waiting finished
Decky Recorder: 2023-05-14 05:36:56,956 INFO Recording stopped!
Decky Recorder: 2023-05-14 05:36:56,957 INFO Deleted all files in rolling buffer
Decky Recorder: 2023-05-14 05:36:56,957 INFO Disable rolling was called end
Decky Recorder: 2023-05-14 05:36:58,470 INFO Enable rolling was called begin
Decky Recorder: 2023-05-14 05:36:58,470 INFO Is capturing? False
Decky Recorder: 2023-05-14 05:36:58,470 INFO Starting recording
Decky Recorder: 2023-05-14 05:36:58,470 INFO Starting recording for mp4 with mux mp4mux
Decky Recorder: 2023-05-14 05:36:58,470 INFO Is capturing? False
Decky Recorder: 2023-05-14 05:36:58,495 INFO Local File Recording
Decky Recorder: 2023-05-14 05:36:58,496 INFO Setting tmp filepath
Decky Recorder: 2023-05-14 05:36:58,496 INFO Setting local filepath
Decky Recorder: 2023-05-14 05:36:58,496 INFO Making audio pipeline
Decky Recorder: 2023-05-14 05:36:58,510 INFO Audio device output alsa_output.pci-0000_04_00.5-platform-acp5x_mach.0.HiFi__hw_acp5x_0__sink
Decky Recorder: 2023-05-14 05:36:58,510 INFO Command: GST_VAAPI_ALL_DRIVERS=1 GST_PLUGIN_PATH=/home/deck/homebrew/plugins/decky-recorder/bin/gstreamer-1.0 LD_LIBRARY_PATH=/home/deck/homebrew/plugins/decky-recorder/bin gst-launch-1.0 -e -vvv pipewiresrc do-timestamp=true ! vaapipostproc ! queue ! vaapih264enc ! h264parse ! splitmuxsink name=sink muxer=mp4mux muxer-pad-map=x-pad-map,audio=vid location=/dev/shm/Decky-Recorder-Rolling_%02d.mp4 max-size-time=2000000000 max-files=240 pulsesrc device="Recording_alsa_output.pci-0000_04_00.5-platform-acp5x_mach.0.HiFi__hw_acp5x_0__sink.monitor" ! audioconvert ! lamemp3enc target=bitrate bitrate=128 cbr=true ! sink.audio_0
Decky Recorder: 2023-05-14 05:36:58,511 INFO Recording started!
Decky Recorder: 2023-05-14 05:36:58,511 INFO Enable rolling was called end

**Comment by pparmy** [comment]
std-err:
"Failed to set pipeline to PAUSED.
Failed to set pipeline to PAUSED."

std-log:
Setting pipeline to PAUSED ...
Setting pipeline to NULL ...
Freeing pipeline ...
Setting pipeline to PAUSED ...
Setting pipeline to NULL ...
Freeing pipeline ...

**Comment by pparmy** [comment]
unrelated but CryoByte33 made a settings in the the "System Toolbox" plugin enable by default upon boot so this might be a bit of a stretch but he *might* be able to help you..? I have no clue if it's that simple or not but I'd figured I'd tell you anyways.!

**Comment by safijari** [comment]
https://github.com/marissa999/decky-recorder/issues/28

more than likely this
