### ISSUE TITLE
[BUG] Decky recorder sometimes doesn't show anything on the menu

### ISSUE THREAD

**Issue by jess-repos** [marissa999/decky-recorder#53]
when the plugins are clicked and to decky recorder, sometimes there are no menu for it like only the back icon and the title are present. no replay mode option, no start recording button just empty

**Comment by Nekuake** [comment]
Same issue here, but I suspect its root may reside in Decky and not specific plugins as I have seen the same behavior in other plugins.

Can you check if other plugins are impacted?

**Comment by karasuhebi** [comment]
I can confirm this has happened to me with Decky Recorder but also with other plugins. Specifically the one I can recall where it happens quite often is the EmuDeck hotkeys one (I forget the exact name of it)

**Comment by HugLifeTiZ** [comment]
This is a Decky bug, not a bug with this plugin. You can work around it by bringing up the regular Steam menu and then reopening the Decky menu.
