### ISSUE TITLE
replay mode stuck enabled

### ISSUE THREAD

**Issue by prodbyloti** [marissa999/decky-recorder#64]
title. cant turn replay mode off. turning it off, starting a recording then going back shows it on again.

**Comment by EliasGagnef** [comment]
same here, is gets stuck on "on" and I cannot save any recordings as well, it says "Too early" even though I waited for more than 30 seconds

**Comment by Conan179** [comment]
This ist the same
https://github.com/marissa999/decky-recorder/issues/62

**Comment by TheAntVenom** [comment]
this happened due to the new 2.10.4 version of decky loader

**Comment by safijari** [comment]
Closing in favor of #62
