### ISSUE TITLE
Decky recorder stop working since last Decky loader update

### ISSUE THREAD

**Issue by ngtung9279** [marissa999/decky-recorder#66]
Is it just me or every have this issue when you tap Start recording the plugin just jumps to Replay mode and does not record anything

**Comment by Conan179** [comment]
https://github.com/marissa999/decky-recorder/issues/65
https://github.com/marissa999/decky-recorder/issues/64
https://github.com/marissa999/decky-recorder/issues/62

**Comment by safijari** [comment]
Please install the new version from the Testing store

**Comment by Conan179** [comment]
Its Working!

https://github.com/marissa999/decky-recorder/assets/1906242/c3e965f1-196e-447c-99e6-20a123c6337b
