### ISSUE TITLE
decky recorder doesnt work on newest update

### ISSUE THREAD

**Issue by prodbyloti** [marissa999/decky-recorder#67]
on the newest deckyloader and decky recorder, now it writes files but they are all 0B.
![image](https://github.com/marissa999/decky-recorder/assets/142157972/54df9037-9932-475a-bc70-a7420da4b219)

**Comment by Conan179** [comment]
I can't reproduce that. Deckyloader v2.10.5-pre1 works with deckyrecorder - 0.3.0-2ac9913
.Which version do you have installed? how did you do it

**Comment by prodbyloti** [comment]
it does the same thing no matter if its Deckyloader v2.10.5-pre1 or 2.10.3. Deckyrecorder  v0.3.0-2ac9913.

**Comment by prodbyloti** [comment]
> You're probably on main.
> 
> Recorder does not yet work on main and unless Valve fixes a problem in gamescope it won't work when 3.5 launches.

sick. guess im downgrading then

**Comment by FoodFrisbee** [comment]
I can't reproduce that. Deckyloader v2.10.5-pre1 works with deckyrecorder - 0.3.0-2ac9913
.Which version do you have installed? how did you do it

Hello, where is this 0.3.0-2ac9913 build of deckyrecorder? I'm still under the impression that 0.2.1 is the latest build

**Comment by FoodFrisbee** [comment]
I can't reproduce that. Deckyloader v2.10.5-pre1 works with deckyrecorder - 0.3.0-2ac9913
@Conan179  Hello, where is this 0.3.0-2ac9913 build of deckyrecorder? I'm still under the impression that 0.2.1 is the latest build

**Comment by Conan179** [comment]
You have to put the marketplace channel on test
