### ISSUE TITLE
Possibly breaks steamdeck boot

### ISSUE THREAD

**Issue by geeksville** [marissa999/decky-recorder#7]
hi hi,

I'm not sure if this is due to decky-recorder - it might not be, but just mentioning in case you see another report:

I saw this plugin on the testing store and it is a really slick idea.  And it worked for the one test video I tried.  But a strange thing: the next time I rebooted my steamdeck it got stuck in a boot loop with a flickering black screen.  I took at look with top/ps and saw there was some sort of Steam script trying to cope with the Steam UI app not launching and repeatedly relaunching it unsuccessfully.

Alas - I didn't have time to investigate more than that and just reinstalled the Steam userspace apps/config file.

It might not be due to decky-recorder, but I've never had this problem on my steamdeck before.

**Comment by geeksville** [comment]
versions: 
decky 2.6.1-pre2
steamos stable 3.4.4
decky-recorder sorry, don't know but it was whatever was up on the decky testing store yesterday.

**Comment by marissa999** [comment]
Hmm weird. Decky-Recorder shouldnt be able to do that, its not even a root plugin. My suspicion would be that maybe something weird happened with an update for something. the latest steamos beta at least did break quite a lot of things, which required the decky loader itself and a few plugins to get an update. and maybe those decky-loader and decky-plugins-updates affected you somehow? or it was a super weird coincidence. 

i did mention that issue in the decky discord server (https://discord.com/channels/960281551428522045/960284311444131840/1079095551179624569). if i found out anything ill keep this ticket up2date

**Comment by geeksville** [comment]
yeah - the only plausible thing I could think of was possibly the pacman gstreamer install stuff had an issue idk.  could be something totally unrelated.  good luck.  it is a great idea!
