### ISSUE TITLE
[Request] Button visualizer

### ISSUE THREAD

**Issue by hgdagon** [marissa999/decky-recorder#9]
This may out of scope for this project, however a button visualizer is mostly useful when recording videos. I understand that implementing may be quite challenging. However if you do consider implementing it, I'd like to request Steam Deck buttons showing up on the lower right, and redirected input (if any) on the bottom right.

**Comment by marissa999** [comment]
Hmm, yeah I think this is out of the scope of this plugin.

However I wanna implement rtsp-server support. That would allow you to capture the deck via Wifi from a different PC (through OBS), and then somebody could add this functionality in OBS themselves
